version: '3.8'

services:
  client:
    build:
      context: ../client
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ../client:/app
      - /app/node_modules
    networks:
      - fitmeai-network

  server:
    build:
      context: ../server
      dockerfile: ./server/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    volumes:
      - ../server:/app
      - /app/node_modules
    networks:
      - fitmeai-network

networks:
  fitmeai-network:
    driver: bridge
